#!/bin/bash

module load scythe/0.991
module load sickle/1.33

#
# USAGE:
# doScythe fastq1 fastq2
#
# THE SCRIPT USES 3 threads
#

#HOME=$( dirname $( realpath $0 ) );

SICKLE="sickle";
SCYTHE="scythe";

echo "Start trimming at $(date)";

if [[ -f $2 && ! -f trimmed1.fastq.gz ]]; then

ADAPTERS="illumina_adapters.fa";
grep '^###' $0 | cut -c 4- > $ADAPTERS ;

$SICKLE pe -g -t sanger \
	-f <( $SCYTHE -a $ADAPTERS -q sanger $1 } ) \
	-r <( $SCYTHE -a $ADAPTERS -q sanger $2 } ) \
	-o trimmed1.fastq.gz -p trimmed2.fastq.gz -s /dev/null;
#rm $ADAPTERS;

fi

echo "Ended trimming at $(date)";

###>multiplexing-forward
###GATCGGAAGAGCACACGTCT
###>solexa-forward
###AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
###>truseq-forward-contam
###AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
###>truseq-reverse-contam
###AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA
###>nextera-forward-read-contam
###CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
###>nextera-reverse-read-contam
###CTGTCTCTTATACACATCTGACGCTGCCGACGA
###>solexa-reverse
###AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAG
###>PrefixNX/1
###AGATGTGTATAAGAGACAG
###>PrefixNX/2
###AGATGTGTATAAGAGACAG
###>Trans1
###TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG
###>Trans1_rc
###CTGTCTCTTATACACATCTGACGCTGCCGACGA
###>Trans2
###GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG
###>Trans2_rc
###CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
###>PrefixPE/1
###AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT
###>PrefixPE/2
###CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT
###>PCR_Primer1
###AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT
###>PCR_Primer1_rc
###AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
###>PCR_Primer2
###CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT
###>PCR_Primer2_rc
###AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG
###>FlowCell1
###TTTTTTTTTTAATGATACGGCGACCACCGAGATCTACAC
###>FlowCell2
###TTTTTTTTTTCAAGCAGAAGACGGCATACGA
###>TruSeq2_SE
###AGATCGGAAGAGCTCGTATGCCGTCTTCTGCTTG
###>PrefixPE/1
###TACACTCTTTCCCTACACGACGCTCTTCCGATCT
###>PrefixPE/2
###GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT
###>PE1_rc
###AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA
###>PE2_rc
###AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
